Algoritmo "Dardo Distancia"

Var
A, B, C, maior: real

Inicio
Escreval("Primeiro Valor: ")
leia (A)
Escreval("Segundo Valor: ")
leia (B)
Escreval("Terceiro Valor: ")
leia (C)
     Se (a > b) e (a>c) ENTAO
     maior <- a
     SENAO
     se b > c entao
     maior <- b
     SENAO
     maior <- c
                   fimse
                   fimse

         Escreval("MAIOR DISTÂNCIA = ", maior:4:2)


Fimalgoritmo